name: Sample workflow

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    prettier:
        runs-on: ubuntu-latest # Specifies that the job runs on the latest version of Ubuntu.

        steps:
            # Checks out the repository code to the workflow runner.
            - uses: actions/checkout@v3

            - name: always
              run: exit 0
